alipan:
  # 根节点文件夹ID，默认为root
  parent_file_id: root
  # 阿里云盘API，默认不改动
  api_url: https://api.aliyundrive.com/v2
  # 阿里云盘开放平台
  open_api_url: https://open.aliyundrive.com
  # 开发者应用AppId
  app_id: 432fe7ab15fd4ce7bc27c1c407eab9a9
  # 开发者应用AppSecret
  app_secret: a8b0xxxxxxxxxxxxxxxxxxxxx
  # AList开发者获取token
  oauth_token_url: https://pan.rawchen.com/api/token
  # 自定义配置存放密码的文件名
  password_file_name: password

server:
  port: 8899

spring:
  application:
    name: AliPan
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**

  # 缓存
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=5m

  # 热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  # 模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: true
    servlet:
      content-type: text/html

  # MVC
  mvc:
    static-path-pattern: static/**

logging:
  level:
    root: info
#    org.springframework.web: trace
