alipan:
  # 根节点文件夹ID，默认为root
  parent_file_id: root
  # 阿里云盘API，默认不改动
  api_url: https://api.aliyundrive.com/v2
  # 阿里云盘请求来源
  referer_url: https://www.aliyundrive.com/
  # 自定义配置存放密码的文件名
  password_file_name: password

server:
  port: 8899

spring:
  application:
    name: AliPan
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**

  # 热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  # 模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: true
    servlet:
      content-type: text/html

  # MVC
  mvc:
    static-path-pattern: static/**

logging:
  level:
    root: info
#    org.springframework.web: trace
